[build]
  publish = "."
  command = ""

[[headers]]
  for = "/assets/Fotos-opt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/tailwind.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
